# Generated by Django 5.2 on 2026-04-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('crn', models.TextField(blank=True, db_column='CRN', null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('href', models.TextField(blank=True, null=True)),
                ('professor_names', models.TextField(blank=True, null=True)),
                ('class_days', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('start_times', models.TextField(blank=True, null=True)),
                ('end_times', models.TextField(blank=True, null=True)),
                ('units', models.FloatField(blank=True, null=True)),
                ('college_name', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('load', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('waitlist_load', models.IntegerField(blank=True, null=True)),
                ('waitlist_capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['name', 'college_name', 'crn'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('num_rating', models.IntegerField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('prof_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'professors',
                'ordering': ['last_name', 'first_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MajorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('institution', models.CharField(blank=True, max_length=140)),
                ('overview', models.TextField(blank=True)),
                ('assist_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['institution', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequirementArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('short_label', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('minimum_units', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('minimum_courses', models.PositiveSmallIntegerField(default=1)),
                ('course_hints', models.TextField(blank=True, help_text='Comma-separated course codes or prefixes to surface as likely SMCCD matches.')),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['path', 'sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransferPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('audience', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticulationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smccd_course_text', models.CharField(blank=True, max_length=160)),
                ('target_institution', models.CharField(max_length=140)),
                ('target_requirement', models.CharField(max_length=180)),
                ('assist_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('source_course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guide.course')),
            ],
            options={
                'ordering': ['target_institution', 'target_requirement', 'smccd_course_text'],
            },
        ),
        migrations.CreateModel(
            name='MajorRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('course_hints', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('major_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='guide.majorplan')),
            ],
            options={
                'ordering': ['major_plan', 'sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=80)),
                ('custom_label', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.requirementarea')),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guide.course')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.transferpath')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='requirementarea',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='guide.transferpath'),
        ),
        migrations.AddField(
            model_name='majorplan',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guide.transferpath'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementarea',
            unique_together={('path', 'name')},
        ),
    ]
