# Generated by Django 5.2 on 2026-04-22 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_seed_transfer_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulationrule',
            name='major_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulations', to='guide.majorplan'),
        ),
    ]
