# Generated by Django 5.2 on 2026-04-22 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_articulationrule_major_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_college', models.CharField(choices=[('CSM', 'College of San Mateo'), ('SKYLINE', 'Skyline College'), ('CANADA', 'Canada College')], max_length=20)),
                ('target_institution', models.CharField(db_index=True, max_length=140)),
                ('assist_url', models.URLField(unique=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_college', 'target_institution'],
                'indexes': [models.Index(fields=['source_college', 'target_institution'], name='guide_agree_source__f38f86_idx')],
                'unique_together': {('source_college', 'target_institution')},
            },
        ),
        migrations.CreateModel(
            name='AgreementMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assist_url', models.URLField(blank=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='guide.agreement')),
            ],
            options={
                'ordering': ['agreement', 'name'],
                'unique_together': {('agreement', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CourseEquivalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smccd_course_code', models.CharField(max_length=50)),
                ('smccd_course_name', models.CharField(blank=True, max_length=200)),
                ('smccd_units', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('target_course_code', models.CharField(max_length=50)),
                ('target_course_name', models.CharField(blank=True, max_length=200)),
                ('target_units', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('prerequisites', models.TextField(blank=True, help_text='Prerequisites for the target course')),
                ('conditions', models.TextField(blank=True, help_text='Special conditions or notes')),
                ('is_articulated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalences', to='guide.agreementmajor')),
            ],
            options={
                'ordering': ['major', 'smccd_course_code', 'target_course_code'],
                'indexes': [models.Index(fields=['major', 'smccd_course_code'], name='guide_cours_major_i_f48d34_idx'), models.Index(fields=['major', 'target_course_code'], name='guide_cours_major_i_e364b6_idx')],
                'unique_together': {('major', 'smccd_course_code', 'target_course_code')},
            },
        ),
    ]
