# Generated by Django 5.2 on 2026-04-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_agreement_agreementmajor_courseequivalence'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agreement',
            name='academic_year_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='source_institution_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='target_institution_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreementmajor',
            name='assist_key',
            field=models.CharField(blank=True, db_index=True, max_length=260),
        ),
        migrations.AddField(
            model_name='courseequivalence',
            name='course_conjunction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='courseequivalence',
            name='group_conjunction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='courseequivalence',
            name='raw_template_cell_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='courseequivalence',
            name='conditions',
            field=models.TextField(blank=True, help_text='Special conditions, advisories, or no-articulation notes'),
        ),
    ]
