# Generated by Django 5.2 on 2026-04-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_agreement_academic_year_agreement_academic_year_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseequivalence',
            options={'ordering': ['major', 'smccd_course_code', 'target_course_code', 'raw_template_cell_id', 'source_group_position', 'source_course_position']},
        ),
        migrations.AlterUniqueTogether(
            name='courseequivalence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseequivalence',
            name='source_course_position',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='courseequivalence',
            name='source_group_position',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterUniqueTogether(
            name='courseequivalence',
            unique_together={('major', 'raw_template_cell_id', 'source_group_position', 'source_course_position', 'smccd_course_code', 'target_course_code')},
        ),
        migrations.AddIndex(
            model_name='courseequivalence',
            index=models.Index(fields=['major', 'raw_template_cell_id'], name='guide_cours_major_i_302a35_idx'),
        ),
    ]
