# Generated by Django 5.2 on 2026-04-24 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_alter_courseequivalence_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='guide.course')),
            ],
            options={
                'ordering': ['course__college_name', 'course__name', 'created_at'],
                'unique_together': {('session_key', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentMajorCourseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equivalence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='guide.courseequivalence')),
            ],
            options={
                'ordering': ['equivalence__major__agreement__source_college', 'equivalence__smccd_course_code', 'equivalence__major__agreement__target_institution'],
                'unique_together': {('session_key', 'equivalence')},
            },
        ),
    ]
